# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83b9a17c4c46c34223d9dea120465515986b9bdddd9c5f48547cb6e1b87b4a84a5f3abbb8429db16ab0a413bb27c26f82a904d0fa9e828c47361cc66374cba88

test:
  secret_key_base: b392f530831384b1c26eeb21ef99b5bc7cb0f64f97c025e6c08c5316b846e78c8b37aba8f92f148fa7e734d65b2e37acc09f66ef996a1f08b2bd1a52d6165506

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
